apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-controller-config
  namespace: unifi
spec:
  storageClassName: default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "5Gi"