apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-controller-config
  namespace: unifi
spec:
  capacity:
    storage: "5Gi"
  hostPath:
    path: "/configs/unifi-controller"
  storageClassName: default
  accessModes:
    - ReadWriteMany